# -*- coding: utf-8 -*-
"""RevisionofContents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11isU0hZYWvO3Wk9GJdlA_vOnufTamZwl
"""

#Odd Even Checker

def OddEven(number):
    if number % 2 == 0:
        return "Number is Even"
    else:
        return "Number is Odd"

print(OddEven(int(input("Enter a Number:"))))

# Calculator

print("Welcome to the Calculator")
usercontinue = True
while usercontinue != False:
    choice = int(input("\nEnter your choice of operation:\n1. Addition\n2. Subtract\n3. Multiply\n4. Divide\n"))
    match choice:
        case 1:
            num1 = int(input("Enter First Number:"))
            num2 = int(input("Enter Second Number:"))
            print("Addition of these numbers is", num1 + num2)
        case 2:
            num1 = int(input("Enter First Number:"))
            num2 = int(input("Enter Second Number:"))
            print( "Subtraction of these numbers is",num1 - num2)
        case 3:
            num1 = int(input("Enter First Number:"))
            num2 = int(input("Enter Second Number:"))
            print("Multiplication of these numbers is", num1 * num2)
        case 4:
            num1 = int(input("Enter First Number:"))
            num2 = int(input("Enter Second Number:"))
            print("Division of these numbers is", num1 * num2)
        case _:
            print(  "Your entered a wrong choice")

    stop_continue = input("\nDo you want to continue? (Y/N) \t")
    if stop_continue.upper() == "Y":
        usercontinue = True
    elif stop_continue.upper() == "N":
        usercontinue = False
    else:
        print("You entered wrong choice, Closing the Calculator")
        usercontinue = False

# Number Guessing Game

'''
steps:
1) decide a secret number manually
2) initialize a counter = 1 and guess
3) create a function which compares the guess to the secret number and continues till the  guess is right
4) return counts of guesses and the result

'''
def guessTheNumber(key):
    guess = int(input("Enter your guess:"))
    counter = 1
    while guess != key:
        counter +=1
        new_guess = int(input("Wrong guess! Try again: "))
        guess = new_guess
    if counter==1:
      print("\nBrilliant, You guessed it in First Try")
    else:
      print("\nYou got it !!")
      print ("You took", counter,"guesses")

print("Welcome to the Ussy_Plays_Guessy:\nTry to Guess my Secret Number")
secret_num = 13

guessTheNumber(secret_num)

# Frequency Counter

"""
Approach:
1) Use of dictionary
2)traverse through the string,
3)if the character is present in the string, add the count
4) else assign value of the character as 1 and add to the list
"""

def freq_Count(word):
    res = {}
    for char in word:
        if char in res:
            res[char] += 1
        else:
            res[char] = 1

    return res

input_word = input("Enter the word:")
print(freq_Count(input_word))

#Student Marks Analyzer:

"""
Approach:
1) take the array as input to the functions for average, highest, lowest and passcount
2) implement average of marks
3) implement finding highest marks
4) implement finding the lowest marks
5) implement pass count of subjects
"""

def average(arr):
    length = len(arr)
    sum = 0
    for i in range(len(arr)):
        sum += arr[i]
    return sum/length

def highest(arr):
    length = len(arr)
    if length == 0:
        return -1
    highest = arr[0]
    for i in range(1,len(arr)):
        if arr[i]> highest:
            highest = arr[i]
    return highest

def lowest(arr):
    length = len(arr)
    if length == 0:
        return -1
    lowest = arr[0]
    for i in range(1,len(arr)):
        if arr[i]< lowest:
            lowest = arr[i]
    return lowest

def pass_count(arr):
    count = 0
    for marks in arr:
        if marks > 40:
            count+= 1

    return count
list_of_marks= [78,65,90,88,39]

print("Average of the subjects is:", average(list_of_marks))
print("Highest marks from subjects is:", highest(list_of_marks))
print("Lowest marks from subjects is:", lowest(list_of_marks))
print("You have passed in", pass_count(list_of_marks),"subjects")

