# -*- coding: utf-8 -*-
"""Day-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duRyau8H2IGFB78xTVMCqtm_WuqwXxnL
"""

# problem 01 : Reverse string, without using [::-1]:

def Reverse_str(msg):
    length = len(msg)
    new_str = ""
    for char in range (length):
        new_str= new_str +  msg[ length - char -1 ] # We cannot use append here

    return new_str

user_input = input("Enter a msg: ")

print(Reverse_str(user_input))

# Character Frequency Counter

"""
two ways:
1) accessing each element in the string message and incrementing the count of unique characters on occurrence.
2) accessing one character and hold it by traversing string for each character count and getting rid of character and keep doing it till the string is empty.

(2) one is harder to get through because it will consume memory for each new string formed after each character count, and might get to n^2 or even n^3 complexity.
"""

#Pseudocode:
"""
1) make empty dictionary
2) traverse through message
3) take each character if it is in dictionary as key add the value, else create a new key and assign its value to 1.
4) return the final dictionary as output
"""

def Freq_counter(message):
    res = {}
    for char in message:
        if char in res:
            res[char] = res[char] +1
        else:
            res[char] = 1
    return res

msg = input("Enter a message: ")
print(Freq_counter(msg))

"""
First Non-Repeating Character

Input:

"aabbcddee"
"""

def firstNonRepeatingChar( input_msg ):
  res = {}

  for char in input_msg:
    if char in res :
      res[char] = res[char] + 1
    else:
      res[char] = 1
    # print(char, res[char])

  # print(res)
  # print("Second loop")
  for e in res:
    # print(e)
    if res[e] == 1:
      return e

  return -1   # case if there is no such character in message

user_input = input(" Enter a message: ")

firstNonRepeatingChar(user_input)

#Linear Search

def Linear_Search(arr, key):
    for idx in range(len(arr)):
        if arr[idx] == key:
            return idx

    return -1

arr = [ 3,2,1,5,7,0]
key = 1

Linear_Search(arr,key)

import math
def SecondLargest (list1):
    largest = - math.inf
    second_largest = - math.inf

    for i in range (len(list1)):
        if list1[i] > largest:
            second_largest = largest
            largest = list1[i]

            print(largest, second_largest)
        if list1[i] < largest and list1[i] > second_largest:
            second_largest = list1[i]
            print(largest, second_largest)

    return second_largest

arr = [5,4,9,2]

SecondLargest(arr)

#Most frequent element:

def MostFrequent(num_list):
    res={}
    for e in num_list:
        if e not in res:
            res[e] = 1
        else:
            res[e] = res[e] + 1

    frequencies = 0
    arr = []
    for key in res:
        if frequencies < res[key]:
            frequencies = res[key]
            arr = arr + [key]

    return arr[len(arr)-1]

num_list = [1,2,3,4]
MostFrequent(num_list)

