# -*- coding: utf-8 -*-
"""Revision

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZcbKe0ml_RGL3WKsyzx1AEOW1NuOYjYy

Revision of Previous codes by Reimplimentation
"""

# 1) Reverse Number Problem.

def Reverse_Number(original): # 1234
    reversed = 0
    while (original > 0) :
        digit  = original % 10    # 4 , 123 -> 3
        reversed = digit + reversed * 10    # 4 + 0*10, 3 + 4*10 -?  43
        original = original // 10 # 1234 // 10 -> 123

    return reversed

user_number = int(input("Enter a number: "))
print("Reverse of number is:", Reverse_Number(user_number))

# Armstrong Number
# The sum of cube of each digit equals to the number itself

def Armstrong_Number(num):
    cube_sum = 0
    original_num = num  # important to store as num will change in loop
    while num > 0:
        digit =  num % 10
        cube_sum = (digit ** 3) + cube_sum
        num = num // 10

    if original_num == cube_sum:
        return "Armstrong Number"

    else:
        return "not Armstrong Number"

user_number = int(input("Enter a number: "))
print("The number is:", Armstrong_Number(user_number))

# Fibonacci Series
# Sequence is : 0 1 1 2 3 5 8...

def firstNFibonacci(number):
    first = 0
    second = 1
    if number <= 0 :
        return -1
    elif number == 1 :
        return 0
    else:
        while number > 0:
            print(first, end = " ")
            third = first + second      # 1 + 0, 1 + 1, 1 + 2
            first = second    # 1, 1 , 2
            second = third     # 1+0, 2, 3
            number = number - 1

user_input = int(input("Enter the number you want Fibonacci seried to: "))
firstNFibonacci(user_input)

# Largest Element in List

def LargestElement(list1):
    elements = len(list1)
    if elements == 0:
        return "List is Empty"
    largest = list1[0]

    for e in list1:
        if largest < e:
            largest = e

    return  largest

list1 = [9,4,8,4,5,11,12,1,14,13] #[]

LargestElement(list1)

# Guess Number Game


def Guess_the_Number(u_input, secret):
    counter = 1

    while u_input != secret:
        print("Wrong Guess!")
        counter = counter + 1
        u_input = int(input("Enter your new guess:"))

    return "Correct!! You took", counter, "attempts"

input1 = int(input("Enter a guess: "))

secret_msg = 7 #manually set

Guess_the_Number(input1, secret_msg)