# -*- coding: utf-8 -*-
"""Day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1850r-sWnoPVrllrjQg5v4bOkmhBMUG_5
"""

print("Hello Aditya, Welcome to Python") 

name = input("Enter your name: ")
print( "Hello", name)

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("Addition: ", num1+ num2)
print("Subtraction: ", num1-num2)
print("Multiplication: ", num1*num2)
print("Division: ", num1/num2)

def OddEven( n):
  if n%2 == 0:
    print ("Even")
  else:
    print("Odd")

Number = int(input("Enter a number: "))
OddEven(Number)

def number_nature(n):
  if n > 0 :
    return "Positive"
  elif n==0 :
    return "Zero"
  else:
    return "Negative"

number = int(input("Enter a number : "))
number_nature(number)

def largestnumber(a,b,c):
  if a>b and a>c:
    print(a, "is the largest number")
  elif b>a and b>c:
    print(b, "is the largest number")
  else:
    print(c, "is the largest number")

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
num3 = int(input("Enter third number:"))

largestnumber(num1,num2,num3)

def firstnNumbers(n):
  for i in range(1, n+1):
    print(i)

number = int(input("Enter a number: "))
firstnNumbers(number)

def SumOfNumbers(n):
  sum = 0
  for i in range(1, n+1):
    sum = sum + i
  print(sum)

number = int(input("Enter a number: "))
SumOfNumbers(number)

def Table (n):
  for i in range(1, 11):
    print(n, "*", i, "=", n*i)

number = int(input("Enter a number: "))
Table(number)

def ReverseNumber(n):
  reverse = 0
  while n>0:
    digit = n%10
    reverse = reverse*10 + digit
    n = n//10
  print(reverse)

number = int(input("Enter a number: "))
ReverseNumber(number)



def isPalindrome(n):
  rev = 0
  number = n
  while n > 0:
    digit = n%10
    rev = rev*10+ digit
    n = n//10
  if number == rev:
    print("The number is a Palindrome")
  else:
    print("The number is not Palindrome")

number = int(input("Enter a number: "))
isPalindrome(number)

def countDigits(n):
  count = 0
  while n > 0:
    n = n//10
    count = count + 1
  return count

number = int(input("Enter a number: "))
print(countDigits(number))

def Factorial(n):
  fact = 1
  if n == 0:
    return 1
  elif (n<0):
    return -1
  else:
    while n>0:
      fact = fact * n
      n = n-1
    return fact

number = int(input("Enter a number: "))
Factorial(number)

# Bonus Question

def Star_Pattern(n):
  for i in range ( 0, n):
    for j in range (0, i+1):
      print("*" , end = " ")
    print ("\n")



number = int(input("Enter a number: "))
Star_Pattern(number)

def isPrime(n):
  if n==1 or n ==2 :
    return True

  for i in range(2,n):
    if n%i == 0:
      return False
    else:
      continue
  return True

number = int(input("Enter a number: "))
if isPrime(number): print("Prime")
else: print("Not Prime")

