# -*- coding: utf-8 -*-
"""Mini_Project_Contact_Book

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJn2vrAzxqEtpNo4RkPZA82_6ugOXGfG
"""

# -*- coding: utf-8 -*-
"""Mini_Project_Contact_Book

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJn2vrAzxqEtpNo4RkPZA82_6ugOXGfG
"""

# CLI interface for a contact book:
"""
Approach/ Work Flow:
    we need a loop for user for their choices.
    each choice is given a seperate function to handle the case.
    to exit the loop, we need a flag until the choice of exit is made it stays True else False.
"""

def add_Contact(contact, value):
    if contact == "":
        return "Cannot add"
    if (contact in contacts) and contacts[contact] == value:
        return "Contact already exists"
    elif (contact in contacts) and contacts[contact] != value:
        contacts[contact] += " , " + value
    else:
        contacts[contact] = value

def search_Contact(key):
    if key in contacts:
        return key, contacts[key]
    else:
        return "Contact doesn't exist"

def display_Contact():
    if contacts == {}:
        print("Contact list is empty")

    print("---------CONTACT-LIST----------")
    total = len(contacts)
    print("\nTotal Contacts: (", total, ")")
    for i,contact in enumerate(contacts):
        print(i+1,contact,":", contacts[contact] )


def delete_contact(contact) :
    if contact in contacts:
        del contacts[contact]
        print("Contact has been deleted")
    else:
        print( "Contact is not in Contact list")

contacts = {}
flag = True
while flag:
    print("\n**What do you want to do now?\n 1) Add a contact\n 2) Search for a contact\n 3) Display all Contacts\n 4) Delete Contact\n 5)Exit")


    # Handles the exception of any invalid input by user
    try:
        choice = int(input("Your choice? -> "))
    except:
        print("Invalid input")
        continue

    match choice:
        case 1:
            contact = input("Name of person: ")

            #if name is empty we will move on to next iteration
            if contact == "":
                print("Please give the name")
                continue
            value = input("Contact:")
            add_Contact(contact, value)
        case 2:
             key = input("Which Contact to Search? ")
             print(search_Contact(key))
        case 3:
            print(display_Contact())
        case 4:
            contact = input("Which contact do you want to Delete: ")
            delete_contact(contact)
        case 5:
            print("Thanks for using Me")
            flag = False
        case _:
            print("There is no such Operation to perform. Please select again")