# -*- coding: utf-8 -*-
"""Revision_D5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOnYfFY9EnR6nPhJ2ASG7mYRoPMFcbyS
"""

#Best Profit Problem

def bestProfit(array1):
    min = array1[0]
    max_profit = 0
    for stock_price in array1:
        current_profit = stock_price - min

        if max_profit < current_profit:
            max_profit = current_profit

        if stock_price < min:
            min = stock_price

    return max_profit

stocks = [9,4,2,6, 1,3,4,2]

print(bestProfit(stocks))

#Most Frequent Number:

def mostFrequent(numbers_list):
    element_track = {}
    for e in numbers_list:
        if e in element_track:
            element_track[e] += 1
        else:
            element_track[e] = 1
    counter = 0
    freq = None
    for e in element_track:
        if element_track[e] > counter:
            counter = element_track[e]
            freq = e

    return freq
numList = [9,4,2,6,1,1,1,3,4,2]
print(mostFrequent(numList))