# -*- coding: utf-8 -*-
"""Text Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKwASLfLi2-lx5Ym5IQbEgSyJlZXfkNA

Mini Implementation Task (MiniProject):
**Text Analyzer**
"""

def CountVowels(word):
    vowels = {"a","e","i","o","u"}
    counter = 0
    for char in word:
        if char in vowels:
            counter += 1
    return counter

def strReverse(word):
    result= ""
    for e in word:
        result = e + result
    return result


def checkPalindrome(str1):
    left = 0
    right = len(str1) - left - 1

    while left < (len(str1)//2)+ 1:
        if str1[left] != str1[right]:
            return False
        left += 1
        right -= 1

    return True

def charFrequency(word):
    freq = {}
    for char in word:
        if char in freq:
            freq[char] += 1
        else:
            freq[char] = 1
    return freq

user_input = input("Enter the word you want to perform operations on:\n")
input_word = user_input.lower()
close = False
while close != True:
    choice = int(input("\nWhich operations would you like to perform\n1. Count vowels\n2. Reverse text\n3. Check Palindrome\n4. Character frequency\n5. Exit\n"))
    match choice:
        case 1:
            print(CountVowels(input_word))
        case 2:
            print(strReverse(input_word))
        case 3:
            print(checkPalindrome(input_word))
        case 4:
            print(charFrequency(input_word))
        case 5:
            print("Thanks!")
            close = True
        case _:
            print("ERROR!! You Entered the wrong choice")