# -*- coding: utf-8 -*-
"""Day-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRz60gtPWZIvaZz31TawuCpz1gYc2PaY
"""

#Functions:

# 1. Square of a number
def squareOfNumber(n):
  return n*n

number = int(input("Enter a number: "))
print("Square of",number, "is:",squareOfNumber(number))

# 2. Larger number of Two Numbers

def LargerNumber(x,y):
  if x > y :
    return x
  elif y > x:
    return y
  else: # this case if for the equal numbers
    return "Wait\nBoth are Equal"

num1 = int(input("Enter First Number: "))
num2 = int(input("Enter Second Number: "))
print("Larger Number is:",LargerNumber(num1,num2))

# 3. Function to count number of vowels in a string

def vowelCounter(str1):
  if str1 == "":
    return 0
  lower_str = str1.lower() # to make sure there is no logic error in cases of string
  count = 0
  for i in range(0, len(lower_str)):
    if (lower_str[i] == "a" or lower_str[i] =="e" or lower_str[i] =="i" or lower_str[i] == "o" or lower_str[i] =="u"):
      count = count + 1
    else:
      continue
  return count

msg = input("Enter a string: ")
print("Number of Vowels in \"",msg,"\"is:",vowelCounter(msg))

# Practicing Lists

# Problem 1:  Sum of List

def Sum_of_List (arr):
  sum = 0
  for i in range(0, len(arr)):
    sum = sum + arr[i]
  return sum

array1 = [3,15,62,23,12,90]

print(Sum_of_List(array1)) # We can take array from user using loops

# Problem 2: Largest element in list

def LargestElement(arr):
  if(len(arr) == 0):
    return -1
  largest = arr[0]
  for i in range (0, len(arr)):
    if arr[i] > largest:
      largest = arr[i]
  return largest

array1 = [3,15,62,23,101,90]

print(LargestElement(array1))

# Problem 3: Count Even Numbers

def Even (arr):
  count =0
  for i in range(0, len(arr)):
    if arr[i] % 2 == 0:
      count = count +1
  return count

print(Even([3,18,62,23,101,90]))

# Nested Loops

# Problem 1: make a square * pattern of n number

def SquarePattern(num):
  for i in range(0,num):
    for j in range(0,num):
      print("*", end="  ")
    print("\n")

numStar = int(input("Enter a number: "))
SquarePattern(numStar)

# Problem : Reverse Triangle

def RevTriangle(n):
  for i in range(n, 0,-1):
    for j in range (i, 0,-1):
      print("*", end = "  ")
    print("\n")

nums = int(input("Enter a number: "))
RevTriangle(nums)

# First n Fibonacci numbers

def Fibonacci(n):
  first = 0
  second = 1
  if n == 1:
    print(first)
  elif n== 2:
    print (first , second)
  else:
    while n > 0:
      print(first , end = " ")
      third = first + second
      first = second
      second = third
      n = n-1

num = int(input("Enter a number: "))
Fibonacci(num)

# Problem of Armstrong Number
def Armstrong_Number(number):
    sum=0
    container = number
    while number> 0:
        digit = number%10
        sum = sum + (digit ** 3)
        number = number // 10

    if sum == container :
        print("The number is an Armstrong Number")
    else:
        print("The number is not an Armstrong Number")

num = int(input ("Enter your Number:"))
Armstrong_Number(num)

# Mini Challenge

# Problem: create a game in which user has to guess the secret number
#Recursive Method
"""
def guessNumber(n, secretNumber, counter):
  if n != secretNumber:
    print ("Your guess was wrong")
    new_guess = int(input("Enter new Guess: "))
    counter = counter + 1
    return guessNumber(new_guess, secretNumber, counter)
  else:
    return "Your guess was correct after",counter,"attempts"

secretNumber = 7
print("Guess the secret number between 1-10")
guess = int(input("Enter your guess: "))
counter = 1
print(guessNumber(guess, secretNumber, counter))
"""

# Solving by Looping
def GuessNumber(n, SecretNumber):
    count= 1
    while n != SecretNumber:
        print("Your Guess is Wrong, Try again!")
        count = count + 1
        n = int(input("Enter new guess: "))
    print("You are right, You took", count, "attempts!")

guess= int(input("Enter your First guess:"))
SecretNumber = 7

GuessNumber(guess, SecretNumber)

