# -*- coding: utf-8 -*-
"""Day 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBISor4Y8GvErdR67c_ctZ7CeXSQ4UjN

Day_6: String Manipulation and Two Pointer
"""

# Count Vowels Problem

def CountVowels(word):
    vowels = ("a","e","i","o","u")
    counter = 0
    for char in word:
        if char.lower() in vowels:
            counter += 1
    return counter

test_word = "programming"
# test_word = "Aditya" output: 2 if not done char.lower()
print(CountVowels(test_word))

# Reversing a String

def strReverse(word):
    result= ""
    for e in word:
        result = e + result
    return result

word = "python"
print(strReverse(word))

# Check Palindrome String

def checkPalindrome(str1):
    left = 0
    right = len(str1) - left - 1

    while left < (len(str1)//2)+ 1:
        if str1[left] != str1[right]:
            return False
        left += 1
        right -= 1

    return True

word = "madam"
print(checkPalindrome(word))

#  Count Words

def countWords(sentence):
    words_list =  sentence.split()
    return len(words_list)

sentence = "I love Python programming"

print(countWords(sentence))

# First Unique Character

def firstUnique(word):
    freq = {}
    for char in word:
        if char in freq:
            freq[char] += 1
        else:
            freq[char] = 1

    for e in freq:
        if freq[e] == 1:
            return e

    return -1

word = "swiss"
print(firstUnique(word))