# -*- coding: utf-8 -*-
"""Day_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fi0-xH7H8bH1zCV5Hxqangp2rQ4XR-pl
"""

#Running maximum

def runningMax (original_list):
    if len(original_list) == 0 :
        return original_list
    res = []
    maximum = original_list[0]
    for e in original_list:
        if e > maximum:
            res += [e]
            maximum = e
            # print(maximum)
        else:
            res += [maximum]
            # print(maximum)

    return res

arr = [3,1,5,2,8]

runningMax(arr)

# Problem 2 — Running Sum

def Running_Sum(num_List):
    if num_List == []:
        return []
    sum = 0
    res = []
    for e in num_List:
        sum += e
        res += [sum]
    return res

arr = [1,2,3,4]
print(Running_Sum(arr))

# best profit problem:

"""
Approach:
 we can hold profit value for 0 initially and work on progression through list,
 if next state is lesser than today we continue with zero as initial state.
 if it is larger than that then we buy, and compare next state for calculating maximum profit.
"""

# [7,1,5,3,6,4]

def bestProfit (stocks):
    minimum = stocks[0]
    max_profit = 0
    for profit in stocks:
        current_profit = profit - minimum
        if current_profit > max_profit:
            max_profit = current_profit
        if profit < minimum:
            minimum = profit

    return max_profit
stocks = [7,1,5,3,6,4]

print(bestProfit(stocks))

# Rotate list to Right by 1:

def RotateRight(list1):
    if len(list1) == 0:
        return list1
    temp = list1[0]
    list1[0] = list1[len(list1)-1]
    for i in range(1,len(list1)):
        temp1 = list1[i]
        list1[i] = temp
        temp = temp1    #Swapping numbers case
    return list1

arr = []
RotateRight(arr)

#Remove duplicate

def rem_Duplicate(list1):
    container ={}
    res=[]
    for e in list1:
        if e in container:
            container[e] += 1
        else:
            container[e] = 1

    for e in container:
         res += [e]

    return res

arr = [1,2,2,3,1,4]

print(rem_Duplicate(arr))

#valid Password Checker

def PasswordChecker(password):
    lower= {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"}
    upper= {"A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"}
    digits = {'1','2','3','4','5','6','7','8','9','0'}

    if len(password) < 8:
        return "Password is lesser than 8 characters"
    flag_lower = False
    flag_upper = False
    flag_digits = False
    for e in password:
        if  e in lower:
            flag_lower = True
        if e in upper:
            flag_upper = True
        if e in digits:
            flag_digits= True

    if (flag_digits and flag_lower and flag_upper):
        return "Strong Password"

    else:
        return "Password doesn't contain either of Uppercase, Lowercase, Digits"

password = input("Validate your password here: ")
print(PasswordChecker(password))

